# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/connection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14src/connection.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"\x88\x01\n\x0fLocationMessage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\t\x12\x31\n\rcreation_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"W\n\x11\x43onnectionMessage\x12\"\n\x08location\x18\x01 \x01(\x0b\x32\x10.LocationMessage\x12\x1e\n\x06person\x18\x02 \x01(\x0b\x32\x0e.PersonMessage\"\x94\x01\n\x11\x43onnectionRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x0e\n\x06meters\x18\x02 \x01(\x05\x12.\n\nstart_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x10\x43onnectionResult\x12\'\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x12.ConnectionMessage\"\x07\n\x05\x45mpty2A\n\x11\x43onnectionService\x12,\n\x03Get\x12\x12.ConnectionRequest\x1a\x11.ConnectionResultb\x06proto3')



_PERSONMESSAGE = DESCRIPTOR.message_types_by_name['PersonMessage']
_LOCATIONMESSAGE = DESCRIPTOR.message_types_by_name['LocationMessage']
_CONNECTIONMESSAGE = DESCRIPTOR.message_types_by_name['ConnectionMessage']
_CONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['ConnectionRequest']
_CONNECTIONRESULT = DESCRIPTOR.message_types_by_name['ConnectionResult']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
PersonMessage = _reflection.GeneratedProtocolMessageType('PersonMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONMESSAGE,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:PersonMessage)
  })
_sym_db.RegisterMessage(PersonMessage)

LocationMessage = _reflection.GeneratedProtocolMessageType('LocationMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGE,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessage)
  })
_sym_db.RegisterMessage(LocationMessage)

ConnectionMessage = _reflection.GeneratedProtocolMessageType('ConnectionMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONMESSAGE,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionMessage)
  })
_sym_db.RegisterMessage(ConnectionMessage)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionRequest)
  })
_sym_db.RegisterMessage(ConnectionRequest)

ConnectionResult = _reflection.GeneratedProtocolMessageType('ConnectionResult', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONRESULT,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionResult)
  })
_sym_db.RegisterMessage(ConnectionResult)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'src.connection_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_CONNECTIONSERVICE = DESCRIPTOR.services_by_name['ConnectionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONMESSAGE._serialized_start=57
  _PERSONMESSAGE._serialized_end=145
  _LOCATIONMESSAGE._serialized_start=148
  _LOCATIONMESSAGE._serialized_end=284
  _CONNECTIONMESSAGE._serialized_start=286
  _CONNECTIONMESSAGE._serialized_end=373
  _CONNECTIONREQUEST._serialized_start=376
  _CONNECTIONREQUEST._serialized_end=524
  _CONNECTIONRESULT._serialized_start=526
  _CONNECTIONRESULT._serialized_end=585
  _EMPTY._serialized_start=587
  _EMPTY._serialized_end=594
  _CONNECTIONSERVICE._serialized_start=596
  _CONNECTIONSERVICE._serialized_end=661
# @@protoc_insertion_point(module_scope)
